// <auto-generated />
using System;
using GW2Stonks.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GW2Stonks.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615114750_AddItemVolume")]
    partial class AddItemVolume
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GW2Stonks.Data.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("VendorValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Type");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GW2Stonks.Data.Entities.ItemVolume", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("BoughtPerDay")
                        .HasColumnType("int");

                    b.Property<double>("CoverageHours")
                        .HasColumnType("double");

                    b.Property<int>("DemandNow")
                        .HasColumnType("int");

                    b.Property<int>("SoldPerDay")
                        .HasColumnType("int");

                    b.Property<int>("SupplyNow")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ItemId");

                    b.ToTable("ItemVolumes");
                });

            modelBuilder.Entity("GW2Stonks.Data.Entities.Price", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("BuyQuantity")
                        .HasColumnType("int");

                    b.Property<int>("BuyUnitPrice")
                        .HasColumnType("int");

                    b.Property<int>("SellQuantity")
                        .HasColumnType("int");

                    b.Property<int>("SellUnitPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ItemId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("GW2Stonks.Data.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Disciplines")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Flags")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MinRating")
                        .HasColumnType("int");

                    b.Property<int>("OutputItemCount")
                        .HasColumnType("int");

                    b.Property<int>("OutputItemId")
                        .HasColumnType("int");

                    b.Property<int>("TimeToCraftMs")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OutputItemId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("GW2Stonks.Data.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RecipeId", "ItemId")
                        .IsUnique();

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("GW2Stonks.Data.Entities.SyncState", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("LastSyncedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RecordCount")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("GW2Stonks.Data.Entities.ItemVolume", b =>
                {
                    b.HasOne("GW2Stonks.Data.Entities.Item", "Item")
                        .WithOne()
                        .HasForeignKey("GW2Stonks.Data.Entities.ItemVolume", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("GW2Stonks.Data.Entities.Price", b =>
                {
                    b.HasOne("GW2Stonks.Data.Entities.Item", "Item")
                        .WithOne("Price")
                        .HasForeignKey("GW2Stonks.Data.Entities.Price", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("GW2Stonks.Data.Entities.Recipe", b =>
                {
                    b.HasOne("GW2Stonks.Data.Entities.Item", "OutputItem")
                        .WithMany("CraftedBy")
                        .HasForeignKey("OutputItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OutputItem");
                });

            modelBuilder.Entity("GW2Stonks.Data.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("GW2Stonks.Data.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GW2Stonks.Data.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("GW2Stonks.Data.Entities.Item", b =>
                {
                    b.Navigation("CraftedBy");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("GW2Stonks.Data.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
